version: "3.8"
services:
  speedtest_tracker_script:
    build:
      context: ./script
      dockerfile: Dockerfile
    container_name: speedtest_tracker_script
    volumes:
      - ./script/data:/app/data
    restart: always
    environment:
      - APP_MODE=${APP_MODE}
      - WINDOWS_SPEEDTEST_CLI_PATH=${WINDOWS_SPEEDTEST_CLI_PATH}
  speedtest_tracker_api:
    build: ./api
    container_name: speedtest_tracker_api
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - speedtest_tracker_script
    volumes:
      - ./script/data:/app/data
    restart: always
    environment:
      - APP_MODE=${APP_MODE}
      - API_PORT=${API_PORT}
      - FRONTEND_URL_LOCAL=${FRONTEND_URL_LOCAL}
      - FRONTEND_URL_PUBLIC=${FRONTEND_URL_PUBLIC}
  speedtest_tracker_app:
    build: ./app
    container_name: speedtest_tracker_app
    ports:
      - "${APP_PORT}:5173"
    depends_on:
      - speedtest_tracker_api
    restart: always
